### ISSUE TITLE
Position parsing error

### ISSUE THREAD

**Issue by frague59** [bashu/django-watermark#18]
Hi, 

Your watermark work perfectly, but there a little error in `position` parsing : 
At line 139 of watermarker/utils.py, the `determine_position` function check if the argument `position` passed to the function is a str : it is not, but a unicode string. 
You could use basestring checking instead, which support both unicode and str instances.

L139:
```python
     elif isinstance(position, basestring):
```

Good job and thanks !

**Comment by frague59** [comment]
... other parsings MUST be unicode compatible too : prefixed with a **u**.

**Comment by frague59** [comment]
Thanks !

**Comment by frague59** [comment]
Is a new release to pypi planed ? I would like to remove the inclusion of modified django-watermark in my project as soon as possible to use a simple dependency.

Thanks for your quick job again !

**Comment by frague59** [comment]
'scuse me, I just have seen it's done ! sorry about previous message !

**Comment by bashu** [comment]
no problem!
